version: "3.9"
name: "grand-chat"

services:
  db:
    image: postgres:16.0-alpine
    volumes:
      - chatdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=chat
      - POSTGRES_PASSWORD=chat
      - POSTGRES_DB=chat

  backend:
    build: ./api
    command: python manage.py runserver 0.0.0.0:9500
    volumes:
      - ./api:/usr/src/app
    ports:
      - "9500:9500"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - "10080:80"
    depends_on:
      - backend

volumes:
  chatdb: